#
# Conda environment for new chaac fw
#
channels:
    - alvaroprieto
    - conda-forge
    - defaults

dependencies:
    - arm-none-eabi-gcc=9_2020_q2_update
    - cmake-xpack=3.18.3_1
    - make=4.2.1
    - ninja=1.10.1
    - python=3.8.6
    - pip
    - lcov=1.15
    - clang-tools=11.0.0
    - doxygen=1.8.20
    - cppcheck=2.1
    - lizard
    - gcovr
