version: '3.5'

volumes:
  nginx-files:
  chaac-cache:

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    # restart: always
    depends_on:
      - flask
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_server:/etc/nginx/conf.d/default.conf:ro
      - nginx-files:/tmp/files
    networks:
      - chaac-net

  flask:
    image: alvaroops/chaac-frontend-flask:latest
    container_name: flask_server
    depends_on:
      - chaac-cache
    # restart: always
    volumes:
      - ./src:/usr/src/app
      - nginx-files:/tmp/files
      - ./chaac_cfg.yml:/chaac/chaac_cfg.yml
      - chaac-cache:/tmp/chaac_cache
    environment:
      - CONFIG=/chaac/chaac_cfg.yml
    command: gunicorn --workers 5 --bind 0.0.0.0:5000 -m 007 app:app
    networks:
      chaac-net:
        aliases:
          - flask-app
    ports:
        - 5000:5000
  chaac-cache:
    image: alvaroops/chaac-cache:latest
    volumes:
      - ./chaac_cfg.yml:/chaac/chaac_cfg.yml
      - chaac-cache:/tmp/chaac_cache
    environment:
      - CONFIG=/chaac/chaac_cfg.yml

networks:
  chaac-net:
