project.name: "chaac"

project.repositories:
    - apache-mynewt-core
    - mcuboot

repository.apache-mynewt-core:
    type: github
    vers: 0-dev
    user: apache
    repo: mynewt-core


repository.mcuboot:
    type: github
    vers: 0-dev
    user: JuulLabs-OSS
    repo: mcuboot
