version: '3.5'

volumes:
  chaac-db:
    external: true
  nginx-files:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    # restart: always
    depends_on:
      - flask
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_frontend:/etc/nginx/conf.d/default.conf:ro
      - nginx-files:/tmp/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - chaac-net

  flask:
    image: alvaroops/chaac-frontend-flask:latest
    container_name: flask
    # restart: always
    depends_on:
      - chaac-logger
    volumes:
      - chaac-db:/chaac:ro
      - ./flask/app:/usr/src/app
      - nginx-files:/tmp/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE=/chaac/chaac.db
    command: gunicorn --workers 5 --bind 0.0.0.0:5000 -m 007 app:app
    networks:
      chaac-net:
        aliases:
          - flask-app
    ports:
        - 5000:5000

  chaac-logger:
    image: alvaroops/chaac_logger:latest
    container_name: chaac-logger
    # restart: always
    environment:
      - SERIAL_PORT=/dev/ttyACM0
    devices:
      - /dev/ttyACM0
    volumes:
      - chaac-db:/chaac
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  chaac-net:
