version: '3.5'

volumes:
  certs:
  vhost:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: chaac-proxy
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_server:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      chaac-net:
        aliases:
          - chaac-proxy
  cache:
    image: alvaroops/chaac-cache:latest
    container_name: chaac-cache
    restart: always
    environment:
      - CONFIG=/cache/config.yml
    volumes:
      - ./config.yml:/cache/
    networks:
      - chaac-net
    depends_on:
      - nginx

networks:
  chaac-net:
