version: '3.5'

# See https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ for more info

volumes:
  certs:
  vhost:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: chaac-proxy
    # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_server:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      chaac-net:
        aliases:
          - chaac-proxy
  cache:
    image: alvaroops/chaac-cache:latest
    container_name: chaac-cache
    # restart: always
    environment:
      - CONFIG=/cache/config.yml
    volumes:
      - ./config.yml:/cache/
    networks:
      - chaac-net
    depends_on:
      - nginx

  letsencrypt-nginx-proxy-companion:
    #restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
        - NGINX_PROXY_CONTAINER=chaac-proxy
        - NGINX_DOCKER_GEN_CONTAINER=chaac-proxy

networks:
  chaac-net:
