version: '3.5'

volumes:
  nginx-files:

services:
  nginx:
    image: nginx:latest
    container_name: chaac_proxy
    # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_server:/etc/nginx/conf.d/default.conf:ro
      - nginx-files:/tmp/files