version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: chaac-proxy
    # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_chaac_server:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www
      - ./volumes/proxy/certs:/etc/nginx/certs:ro
    networks:
      chaac-net:
        aliases:
          - chaac-proxy
  cache:
    image: alvaroops/chaac-cache:latest
    container_name: chaac-cache
    # restart: always
    environment:
      - CONFIG=/cache/config.yml
    volumes:
      - ./config.yml:/cache/config.yml
    networks:
      - chaac-net
    depends_on:
      - nginx

  letsencrypt-nginx-proxy-companion:
    #restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

networks:
  chaac-net: